make: Class.scala Function.scala Trait.scala mildlyuseful.scala meat.scala salad.scala sandwhich.scala 
	scalac Class.scala
	scalac Function.scala
	scalac mildlyuseful.scala
	scalac meat.scala
	scalac salad.scala
	scalac sandwhich.scala
