make: Byte.scala Short.scala Int.scala Long.scala Float.scala Double.scala Char.scala String.scala Bool.scala Unit.scala Null.scala Nothing.scala Any.scala IntError.scala
	scalac Byte.scala 
	scalac Short.scala
	scalac Int.scala
	scalac Long.scala
	scalac Float.scala
	scalac Double.scala
	scalac Char.scala
	scalac String.scala
	scalac Bool.scala
	scalac Unit.scala
	scalac Null.scala
	scalac Nothing.scala
	scalac Any.scala
	scalac IntError.scala
