make: BadBakery.scala Bread.scala properSourdough.scala userSourdough.scala CompareBreads.scala
	scalac BadBakery.scala
	scalac Bread.scala
	scalac properSourdough.scala
	scalac userSourdough.scala
	scalac CompareBreads.scala